/**
 * Markdown Generator
 * 生成博客文章的Markdown文件
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { config } from './config.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * 生成URL友好的slug
 */
function generateSlug(title, arxivId) {
  // 从arXiv ID生成简洁的slug
  const cleanId = arxivId.replace(/\./g, '');
  const date = new Date().toISOString().split('T')[0];
  return `arxiv-${cleanId}-${date}`;
}

/**
 * 生成中文Markdown文件内容
 */
function generateChineseMarkdown(paper) {
  const { categoryMap } = config;
  const tags = [
    ...paper.suggestedTags,
    ...paper.categories.map(cat => categoryMap[cat]).filter(Boolean),
    'arXiv',
    'AI精选'
  ];

  // 去重
  const uniqueTags = [...new Set(tags)];

  const frontmatter = `---
title: "${paper.title}"
date: "${paper.published}"
summary: "${paper.summary.substring(0, 200).replace(/"/g, '\\"')}..."
tags: ${JSON.stringify(uniqueTags)}
venue: "arXiv Preprint"
status: "preprint"
authors:
${paper.authors.map(name => `  - name: "${name}"`).join('\n')}
arxiv: "${paper.arxivUrl}"
pdf: "${paper.pdfUrl}"
${paper.github ? `github: "${paper.github}"` : ''}
ai_generated: true
filter_score: ${paper.filterScore}
---`;

  const content = `
# ${paper.title}

> 📄 论文链接: [arXiv](${paper.arxivUrl}) | [PDF](${paper.pdfUrl})
${paper.github ? `> 💻 代码仓库: [GitHub](${paper.github})` : ''}
> 🤖 本文由AI自动筛选和总结，内容仅供参考

---

## AI 筛选理由

${paper.filterReason}

**相关度评分**: ${paper.filterScore}/10

---

${paper.summary_zh || '## 论文摘要\n\n' + paper.summary}

---

## 原始摘要 (English)

${paper.summary}

---

## 论文信息

- **arXiv ID**: ${paper.arxivId}
- **发布日期**: ${paper.published}
- **更新日期**: ${paper.updated}
- **分类**: ${paper.categories.join(', ')}
- **作者**: ${paper.authors.join(', ')}

---

*本文由AI Agent自动生成于 ${new Date().toISOString().split('T')[0]}。如有理解偏差，请以原论文为准。*
`;

  return frontmatter + '\n' + content;
}

/**
 * 生成英文Markdown文件内容
 */
function generateEnglishMarkdown(paper) {
  const { categoryMap } = config;
  const tags = [
    ...paper.suggestedTags,
    ...paper.categories,
    'arXiv',
    'AI Curated'
  ];

  const uniqueTags = [...new Set(tags)];

  const frontmatter = `---
title: "${paper.title}"
date: "${paper.published}"
summary: "${paper.summary.substring(0, 200).replace(/"/g, '\\"')}..."
tags: ${JSON.stringify(uniqueTags)}
venue: "arXiv Preprint"
status: "preprint"
authors:
${paper.authors.map(name => `  - name: "${name}"`).join('\n')}
arxiv: "${paper.arxivUrl}"
pdf: "${paper.pdfUrl}"
${paper.github ? `github: "${paper.github}"` : ''}
ai_generated: true
filter_score: ${paper.filterScore}
---`;

  const content = `
# ${paper.title}

> 📄 Paper: [arXiv](${paper.arxivUrl}) | [PDF](${paper.pdfUrl})
${paper.github ? `> 💻 Code: [GitHub](${paper.github})` : ''}
> 🤖 This article is automatically curated by AI. Content is for reference only.

---

## Why This Paper Was Selected

${paper.filterReason}

**Relevance Score**: ${paper.filterScore}/10

---

${paper.summary_en || '## Abstract\n\n' + paper.summary}

---

## Paper Information

- **arXiv ID**: ${paper.arxivId}
- **Published**: ${paper.published}
- **Updated**: ${paper.updated}
- **Categories**: ${paper.categories.join(', ')}
- **Authors**: ${paper.authors.join(', ')}

---

*Auto-generated by AI Agent on ${new Date().toISOString().split('T')[0]}. Please refer to the original paper for accurate information.*
`;

  return frontmatter + '\n' + content;
}

/**
 * 保存Markdown文件
 */
export function savePaperAsMarkdown(paper) {
  const slug = generateSlug(paper.title, paper.arxivId);
  const outputDir = path.join(__dirname, '../../', config.output.directory);

  // 确保输出目录存在
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  const filePathZh = path.join(outputDir, `${slug}.zh.md`);
  const filePathEn = path.join(outputDir, `${slug}.en.md`);

  // 检查文件是否已存在
  if (fs.existsSync(filePathZh) || fs.existsSync(filePathEn)) {
    console.log(`⚠️  文件已存在，跳过: ${slug}`);
    return null;
  }

  try {
    // 生成并保存中文版本
    const contentZh = generateChineseMarkdown(paper);
    fs.writeFileSync(filePathZh, contentZh, 'utf8');
    console.log(`✅ 已保存中文版本: ${filePathZh}`);

    // 生成并保存英文版本
    if (config.output.generateEnglishVersion) {
      const contentEn = generateEnglishMarkdown(paper);
      fs.writeFileSync(filePathEn, contentEn, 'utf8');
      console.log(`✅ 已保存英文版本: ${filePathEn}`);
    }

    return {
      slug,
      filePathZh,
      filePathEn: config.output.generateEnglishVersion ? filePathEn : null
    };
  } catch (error) {
    console.error(`❌ 保存文件失败 ${slug}:`, error.message);
    throw error;
  }
}

/**
 * 批量保存论文
 */
export function savePapersAsMarkdown(papers) {
  console.log(`\n📝 开始生成 ${papers.length} 篇论文的Markdown文件...\n`);

  const savedFiles = [];

  for (const paper of papers) {
    try {
      const result = savePaperAsMarkdown(paper);
      if (result) {
        savedFiles.push(result);
      }
    } catch (error) {
      console.error(`跳过论文 ${paper.arxivId}: ${error.message}`);
    }
  }

  console.log(`\n✅ 成功生成 ${savedFiles.length} 篇论文的Markdown文件\n`);

  return savedFiles;
}

/**
 * 生成总结报告
 */
export function generateReport(papers, savedFiles) {
  const report = `
# AI Agent 运行报告

**运行时间**: ${new Date().toISOString()}

## 统计信息

- **筛选论文数**: ${papers.length}
- **生成文件数**: ${savedFiles.length}

## 论文列表

${papers.map((paper, i) => `
### ${i + 1}. ${paper.title}

- **arXiv ID**: ${paper.arxivId}
- **评分**: ${paper.filterScore}/10
- **理由**: ${paper.filterReason}
- **标签**: ${paper.suggestedTags.join(', ')}
- **链接**: ${paper.arxivUrl}
`).join('\n')}

## 生成的文件

${savedFiles.map(file => `- ${file.slug}\n  - 中文: ${file.filePathZh}\n  - 英文: ${file.filePathEn || 'N/A'}`).join('\n')}

---

*由 AI Agent 自动生成*
`;

  return report;
}

/**
 * 测试函数
 */
export function testGenerator() {
  console.log('🧪 测试 Markdown Generator...\n');

  const mockPaper = {
    arxivId: '2404.12345',
    title: 'Test Paper: Video Understanding with LLMs',
    summary: 'This is a test paper about video understanding using large language models.',
    authors: ['John Doe', 'Jane Smith'],
    categories: ['cs.CV', 'cs.AI'],
    published: '2024-04-15',
    updated: '2024-04-16',
    arxivUrl: 'https://arxiv.org/abs/2404.12345',
    pdfUrl: 'https://arxiv.org/pdf/2404.12345.pdf',
    filterScore: 9,
    filterReason: '该论文直接解决视频理解问题，使用大语言模型进行多模态学习',
    suggestedTags: ['视频理解', '多模态', 'LLM'],
    summary_zh: '## 核心创新\n\n这是一个测试总结...'
  };

  try {
    const result = savePaperAsMarkdown(mockPaper);
    console.log('\n✅ 测试成功');
    console.log('生成的文件:', result);
  } catch (error) {
    console.error('\n❌ 测试失败:', error.message);
  }
}

// 如果直接运行此文件，执行测试
if (import.meta.url === `file://${process.argv[1]}`) {
  testGenerator();
}
